language: node_js
node_js:
  - 'lts/*'
  - 10
before_script:
  - git config user.name "Travis CI"
  - git config user.email "mail@mail.com"
script:
  - yarn run lint
  - yarn run flow
  - yarn run test
  - yarn run coverage
cache:
  yarn: true
  directories:
    - node_modules
